"""
Entry point for the ARKit Blendshape Generator add-on.

This add-on provides tools for creating and managing ARKit-compatible
blendshapes within Blender. It sets up a custom UI panel, operators for
preparing a mesh (defining a head region and camera rig), creating empty
ARKit shape keys, and stubs for generating each blendshape via an
external generative AI service. The add-on is designed as a starting
point and can be extended with real API calls and geometry solvers.
"""

bl_info = {
    "name": "ARKit Blendshape Generator",
    "author": "Generated by ChatGPT",
    "version": (0, 1, 0),
    "blender": (2, 80, 0),
    "location": "View3D > Sidebar > ARKit Gen",
    "description": "Generate ARKit-compatible blendshapes using generative AI",
    "category": "Animation",
}

import bpy

from .logging_utils import log, log_addon_source
from .properties import ARKITGenSettings
from .ui import ARKITGEN_PT_main_panel
from .operators_setup import (
    ARKITGEN_OT_use_selected_object,
    ARKITGEN_OT_create_head_group,
    ARKITGEN_OT_capture_head_selection,
    ARKITGEN_OT_create_cameras,
    ARKITGEN_OT_create_arkit_shapekeys,
)
from .operators_generate import (
    ARKITGEN_OT_generate_blendshape,
    ARKITGEN_OT_regenerate_blendshape,
    ARKITGEN_OT_generate_all,
)

# List of classes to register/unregister. Order matters for proper
# property cleanup when unregistering.
classes = [
    ARKITGenSettings,
    ARKITGEN_PT_main_panel,
    ARKITGEN_OT_use_selected_object,
    ARKITGEN_OT_create_head_group,
    ARKITGEN_OT_capture_head_selection,
    ARKITGEN_OT_create_cameras,
    ARKITGEN_OT_create_arkit_shapekeys,
    ARKITGEN_OT_generate_blendshape,
    ARKITGEN_OT_regenerate_blendshape,
    ARKITGEN_OT_generate_all,
]

def register():
    """Register the add-on classes and add the settings to the Scene."""
    from bpy.utils import register_class
    log_addon_source(__file__, __package__ or __name__)
    for cls in classes:
        log(f"Registering class: {cls.__name__}")
        register_class(cls)
    # Attach our settings property group to the Scene type
    bpy.types.Scene.arkit_gen_settings = bpy.props.PointerProperty(
        type=ARKITGenSettings
    )
    log("Scene.arkit_gen_settings pointer property registered")

def unregister():
    """Unregister the add-on classes and remove the settings from the Scene."""
    from bpy.utils import unregister_class
    for cls in reversed(classes):
        log(f"Unregistering class: {cls.__name__}")
        unregister_class(cls)
    # Remove custom property from Scene
    if hasattr(bpy.types.Scene, "arkit_gen_settings"):
        del bpy.types.Scene.arkit_gen_settings
        log("Scene.arkit_gen_settings pointer property removed")
